### ISSUE TITLE
Error: This video is unavailable

### ISSUE THREAD

**Issue by idoor88** [AbelTesfaye/react-native-ytdl#10]
Hi, thanks for your attention,  I got the following code for videoId: SJbOiJ--W8o

          ` ytdl.getInfo('SJbOiJ--W8o', {}, (err, info) => {

                    if (err){
                       
                         console.error("getVideoURL err: ", err);
                    }
                    else{
                        
                        let format = ytdl.chooseFormat(info.formats, { quality: '22' });

                        ...
`
for some reason, I got this error:
Error: This video is unavailable
    at info.js:278
    at info.js:203
    at run (es6.promise.js:75)
    at es6.promise.js:92
    at flush (_microtask.js:18)
    at tryCallOne (core.js:37)
    at core.js:123
    at JSTimers.js:289
    at _callTimer (JSTimers.js:146)
    at _callImmediatesPass (JSTimers.js:194)

Basically, for some videoIds, it throws this error, for some other videoIds, it works fine.

For this videoId: SJbOiJ--W8o, this url works in browser:
https://www.youtube.com/watch?v=SJbOiJ--W8o&feature=youtu.be

My environment:
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 183.45 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 11.4.0 - /usr/local/bin/node
    npm: 6.4.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 23, 25, 26, 27, 28
      Build Tools: 27.0.3, 28.0.2, 28.0.3
      System Images: android-22 | Google APIs Intel x86 Atom, android-27 | Google APIs Intel x86 Atom, android-27 | Google Play Intel x86 Atom, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.1 AI-173.4907809
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: ^16.8.6 => 16.8.6 
    react-native: ^0.60.0 => 0.60.0 
  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native-cn-richtext-editor: 1.0.33
    react-native-git-upgrade: 0.2.7

**Comment by idoor88** [comment]
Also when I do youtube-dl command with this video ID, it generated the video url, which works from  browser, so why this function threw error: ytdl.getInfo('SJbOiJ--W8o', {}, (err, info) => ...?


youtube-dl -g "https://www.youtube.com/watch?v=SJbOiJ--W8o"
WARNING: Unable to extract video title
https://r2---sn-p5qs7nee.googlevideo.com/videoplayback?expire=1564521735&ei=p2BAXcH_B4WXhga3266wCg&ip=8.46.40.253&id=o-AFRv1mAhNIriAjmq84lUKKF0jHf_wlZQ6CBY7g8CEZvK&itag=136&aitags=133%2C134%2C135%2C136%2C160%2C242%2C243%2C244%2C247%2C278&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-p5qs7nee%2Csn-ab5l6nzr&ms=au%2Conr&mv=m&mvi=1&pl=24&initcwndbps=4093750&mime=video%2Fmp4&gir=yes&clen=1651295280&dur=7536.633&lmt=1564462761361508&mt=1564500009&fvip=2&keepalive=yes&c=WEB&txp=7316222&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgaOw9QD6_7zcrndyMpKX-9YKQGFfHT0xtVmLScZDfLDgCIEzpAPm9eh13wfZBRaG4jczC3blK-eTjZCk8lP1d9Y7G&sig=ALgxI2wwRAIgHt-9hYe1_KgNvbhZ9K_8ttAt0ikDd0HGg2yIzAT8wt4CIDbFDgqfEpMCXsauCEUvgEbKV-11sAkwZDPf1ZfntXgb&ratebypass=yes
https://r2---sn-p5qs7nee.googlevideo.com/videoplayback?expire=1564521735&ei=p2BAXcH_B4WXhga3266wCg&ip=8.46.40.253&id=o-AFRv1mAhNIriAjmq84lUKKF0jHf_wlZQ6CBY7g8CEZvK&itag=251&source=youtube&requiressl=yes&mm=31%2C26&mn=sn-p5qs7nee%2Csn-ab5l6nzr&ms=au%2Conr&mv=m&mvi=1&pl=24&initcwndbps=4093750&mime=audio%2Fwebm&gir=yes&clen=115387283&dur=7536.741&lmt=1564476055460550&mt=1564500009&fvip=2&keepalive=yes&c=WEB&txp=7301222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgaOw9QD6_7zcrndyMpKX-9YKQGFfHT0xtVmLScZDfLDgCIEzpAPm9eh13wfZBRaG4jczC3blK-eTjZCk8lP1d9Y7G&sig=ALgxI2wwRQIhAKVH_W-jEUEif44XPQ4SiOnL7VTOR2KEEyBNPDWJC0UCAiAPhRuIu-DMrczr7YSqjYmqITki5-NUlgFH2tQbrW8E7g==&ratebypass=yes

**Comment by jibbex** [comment]
Hello,

there was an issue with the title props. It was fixed a few days ago in [node-ytdl-core/issues/465](https://github.com/fent/node-ytdl-core/issues/465). I implemented the changes. But it seems that the author of this repository is currently not active.

For the moment you can try my fork [https://github.com/jibbex/react-native-ytdl](react-native-ytdl) or you just replace info.js with the content of [info.zip](https://github.com/AbelTesfaye/react-native-ytdl/files/3454890/info.zip)

**Comment by idoor88** [comment]
Hi, Jibbex, thanks for your response, I installed your fork version https://github.com/jibbex/react-native-ytdl, but I still got the same error for some videos: this video is unavailable, so which part in your code fixed the issue?
Thanks

**Comment by jibbex** [comment]
Hello again,

i tried it yesterday and it worked. Maybe the reason is that the video is in deed not available? After a quick test, i checked the url and the video is gone.

 [https://www.youtube.com/watch?v=SJbOiJ--W8o&feature=youtu.be](https://www.youtube.com/watch?v=SJbOiJ--W8o&feature=youtu.be)

You say you have on additional videos this problem? Could you please provide a link?

**Comment by idoor88** [comment]
Hi Jibbex,
I tried with this n1x1Iq1qR6I video ID, it gave me video unavailable error, but  this link works: https://www.youtube.com/watch?v=n1x1Iq1qR6I&feature=youtu.be

**Comment by jibbex** [comment]
Hey idoor,

this is very weird. It works fine with my test code. If you updated react-native-ytdl, I honestly have no idea what went wrong.

```
testDownload = () => {
    ytdl.getInfo('P2VkyILJaWE', {}, (err, info) => {
      if(err) {
        console.log(err);
        return;
      }
      const format = ytdl.chooseFormat(info.formats, { quality: '22' });
      console.log('download url:', format.url);
    })

    ytdl.getInfo('mDV8cYC5J00', {}, (err, info) => {
      if(err) {
        console.log(err);
        return;
      }
      const format = ytdl.chooseFormat(info.formats, { quality: '22' });
      console.log('download url:', format.url);
    })

    ytdl.getInfo('n1x1Iq1qR6I', {}, (err, info) => {
      if(err) {
        console.log(err);
        return;
      }
      const format = ytdl.chooseFormat(info.formats, { quality: '22' });
      console.log('download url:', format.url);
    })
 }

```
![cmd_2019-08-09_00-57-01](https://user-images.githubusercontent.com/8302060/62743518-fefb4a00-ba42-11e9-8c68-8f410be2a278.png)
```
08-08 22:48:00.192 14985 15017 I ReactNativeJS: 'download url:', 'https://r3---sn-4g5edne6.googlevideo.com/videoplayback?expire=1565326081&ei=oaZMXcCUI9CtgAeN17WICw&ip=84.142.212.43&id=o-APMUbXEJbkEAIlT6Em0DbiRll2pwbeG3pcIv1_V-7oKa&itag=22&source=youtube&requiressl=yes&mm=31,29&mn=sn-4g5edne6,sn-4g5e6nss&ms=au,rdu&mv=m&mvi=2&pl=26&initcwndbps=1000000&mime=video/mp4&ratebypass=yes&dur=40049.383&lmt=1564812430234099&mt=1565304379&fvip=3&c=WEB&txp=7216222&sparams=expire,ei,ip,id,itag,source,requiressl,mime,ratebypass,dur,lmt&sig=ALgxI2wwRQIgE9-Yszd5VGsuEF4NhL9oPoioTXu_1hJQ3heXs4O4QbwCIQD4nMqFMqaMSNZuLptXd3HqunRjZk0M2eUb80-POHmSOg==&lsparams=mm,mn,ms,mv,mvi,pl,initcwndbps&lsig=AHylml4wRQIgGEVOhDys1k6E4bcbhJWyt0oe_wu922UgFzMNGFVhV0YCIQD4Bq6LtTMl11-DUlQRcEI3iOeKFcoikUqUbmNj0XrCjA=='
08-08 22:48:00.364 14985 15017 I ReactNativeJS: 'download url:', 'https://r4---sn-4g5e6nes.googlevideo.com/videoplayback?expire=1565326081&ei=oaZMXeiaLI6e8gPt7avIBg&ip=84.142.212.43&id=o-AI0_ABPxQY90Ed_wyVZiMbSA5RAQKJG5wqqJylNF5lSq&itag=22&source=youtube&requiressl=yes&mm=31,26&mn=sn-4g5e6nes,sn-h0jeeney&ms=au,onr&mv=m&mvi=3&pl=26&initcwndbps=1058750&mime=video/mp4&ratebypass=yes&dur=7579.364&lmt=1564802444280113&mt=1565304379&fvip=4&c=WEB&txp=7316222&sparams=expire,ei,ip,id,itag,source,requiressl,mime,ratebypass,dur,lmt&sig=ALgxI2wwRQIgDbFmnwWTiGZ3kGZCP5nSnotqgsP3ZbewxfEfFXRiwGoCIQCZgWcTfwnyyvDkFxcW-zFEaO1AUbFt1U4skfIvm4wPOA==&lsparams=mm,mn,ms,mv,mvi,pl,initcwndbps&lsig=AHylml4wRgIhALbfDk-nK2TGGzqAYBSBzF3K6yhheCMsXSeJT6ebw3FaAiEAgorftNGMDcSh3Xnl9ZLNO9yu9Cd3Z6TXEAK98pX_3bg='
08-08 22:48:00.603 14985 15017 I ReactNativeJS: 'download url:', 'https://r2---sn-4g5ednse.googlevideo.com/videoplayback?expire=1565326082&ei=oaZMXfTzNf2Cx_APpNmSuAE&ip=84.142.212.43&id=o-ACh5wWlxv3O76jS6WmRy4daZzNeSBS_DNzoxDGNC7FUJ&itag=22&source=youtube&requiressl=yes&mm=31,26&mn=sn-4g5ednse,sn-h0jeenl7&ms=au,onr&mv=m&mvi=1&pl=26&initcwndbps=1083750&mime=video/mp4&ratebypass=yes&dur=6410.054&lmt=1564801528805886&mt=1565304379&fvip=2&c=WEB&txp=7216222&sparams=expire,ei,ip,id,itag,source,requiressl,mime,ratebypass,dur,lmt&sig=ALgxI2wwRQIgWAFbJ6oqxTWfpjuKCdclA8KCAbUiHbtHSw5ljBK0Pq8CIQCH2htJ4q7oLmSWqKsmujGWKIt6OBP1FDL_LabVZ7VaZQ==&lsparams=mm,mn,ms,mv,mvi,pl,initcwndbps&lsig=AHylml4wRQIgMZ7VqGi_3hiy1n6fekLtJ_uw38sqqp3sJM93jYOAH3ACIQCA1z5ehgp92aDqB5iZLIm4__oAg7PGcpV95wRxf0G6rA=='
```

 Did you notice that the import changed?

`import ytdl from 'jibbex-react-native-ytdl';`

**Comment by AbelTesfaye** [comment]
Hello,

I just updated and published the library: https://www.npmjs.com/package/react-native-ytdl


@jibbex Thank you for helping with the issues.

**Comment by jibbex** [comment]
Hello @AbelTesfaye ,

I didn't count on you answering any more.

There was another problem with the titles and it seems that is not fixed in the code.

If you change _info.js_ in line 191 ` Object.assign(info, additional);` to:

```
Object.assign(info, additional, {
  // Give the standard link to the video.
  video_url: VIDEO_URL + id,

  // Copy over a few props from `player_response.videoDetails`
  // for backwards compatibility.
  title: info.player_response.videoDetails.title,
  length_seconds: info.player_response.videoDetails.lengthSeconds,
 });
```

You should be able to fix this problem.

I'm sorry if that is the wrong place for it.

[info.js.zip](https://github.com/AbelTesfaye/react-native-ytdl/files/3582365/info.js.zip)

**Comment by AbelTesfaye** [comment]
> I'm sorry if that is the wrong place for it.

fixed! Thanks for pointing this out.
