### ISSUE TITLE
Can't return video info

### ISSUE THREAD

**Issue by Jordan-Morrison** [AbelTesfaye/react-native-ytdl#12]
ytdl.getInfo does not return anything, can only access the video info from within the callback. Need to be able to await for the data to be returned

**Comment by jibbex** [comment]
Greetings,

i'll refer you to an answer from me on the same topic. i hope that helps you.

https://github.com/AbelTesfaye/react-native-ytdl/issues/9#issuecomment-515678955

**Comment by Jordan-Morrison** [comment]
@jibbex thanks for the help! 

That still doesn't quite accomplish what I'm trying to do though. I have a bunch of code, so putting it all inside a .then or a callback would get quite messy.

Would like to do something like this:
```javascript
let info = await ytdl.getInfo(videoID, {});
return info;
```

**Comment by jibbex** [comment]
@Jordan-Morrison  

This was clearly my bad. I should read the question completly before i answer. I edited my post. Please take another look at it.

**Comment by Jordan-Morrison** [comment]
@jibbex It worked! Thank you so much!
