### ISSUE TITLE
"Possible Unhandled Promise Rejection"

### ISSUE THREAD

**Issue by FCjosh** [AbelTesfaye/react-native-ytdl#26]
I'm getting this error: 
<img width="383" alt="Screen Shot 2020-06-30 at 4 01 27 PM" src="https://user-images.githubusercontent.com/47929869/86181549-761e4e80-baeb-11ea-86a2-457751ca8f33.png">

I first got the error when using the "Usage" section code from the ReadMe of this library. I then tried using the code from the example called ytdl-react-native-test-app and got the same error. I made sure that ytdl-react-native, npm, and react-native are the latest versions. I am using an IOS emulator (with xcode).

**Comment by AbelTesfaye** [comment]
This is strange, it might be caused by a bug in react-native on the iOS platform because I just checked the test app on android and it works fine. 

I suspect the issue might be caused when mixing ES6 imports with Node.js require.

Could you please try the following solutions and see if they fix the problem:

> ### Potential solution 1:
> - **Change contents of** `${PATH_YOU_CLONED_THE_REPO}/react-native-ytdl/react_native_ytdl_test_app/node_modules/react-native-ytdl/index.js` **to the following:**
>
> ```javascript
> const ytdl = require('./lib');
> 
> export default ytdl;
> ```


> ### Potential solution 2:
> - **Change contents of** `${PATH_YOU_CLONED_THE_REPO}/react-native-ytdl/react_native_ytdl_test_app/node_modules/react-native-ytdl/index.js` **to the following:**
> ```javascript
> const ytdl = require('./lib');
> 
> module.exports = ytdl;
> ```
> - **Change contents of**  `${PATH_YOU_CLONED_THE_REPO}/react-native-ytdl/react_native_ytdl_test_app/App.js` **(line 29) to the following:**
> ```javascript
> const ytdl = require('react-native-ytdl');
> ```

Please let me know if either of these fixes the issue for you

**Comment by FCjosh** [comment]
I thought I had updated the react-native-ytdl module, but after looking at the module's directory, the update did not work. I properly updated it and now the issue I was having is gone and I got a new issue which I am going to open up a new issue for.
