### ISSUE TITLE
Only latest 30 seconds of HLS feed available.

### ISSUE THREAD

**Issue by deepak-jha-kgp** [AbelTesfaye/react-native-ytdl#31]
I'm using HLS stream to play live videos from youtube. The m3u8 streams, however, have stream data for 30 seconds of video, with a link to the next 30 seconds of video available. This enables me to play the live video smoothly but restricts me from seeking back in the video. I'm using react-native-video(exoplayer) to stream the videos.

**Comment by AbelTesfaye** [comment]
The library doesn't have any APIs to pre-buffer the segments in the m3u8 playlist. It simply deciphers the HLS playlist url then returns urls of the segments.

So, for the current version at least, It's up to the user to decide how to use the raw segment urls. That being said, making the m3u8 playlist url available is a great idea and will probably be added in the next release.

Thanks

**Comment by lesmo** [comment]
I'm not sure you'll be able to make seeking work easily with HLS (if at all, I don't think HLS is meant to allow seeking). Like Abel said, it's out of the scope of this lib... perhaps people on `react-native-video` repo can be more helpful 🙃

**Comment by deepak-jha-kgp** [comment]
There is no problem with HLS and seeking, seeking works just fine with HLS and is supported by react-native-video and exoplayer. But the problem here(for us) is getting the part of live video already elapsed during a live session, as the current API gives us m3u8 containing urls for **past 30 seconds only**. However, once the live streaming ends, m3u8 for the whole session is usually available and works well, just seconds after the live session is over.

**Comment by AbelTesfaye** [comment]
Hey, check the latest update. This library should return a url for the m3u8 playlist now. 

You can plug that directly into react-native-video and get a live stream that will last for more than 30 seconds but I've noticed seeking still doesn't work with their player, but it seems to work on other players like [this one](https://players.akamai.com/players/hlsjs) (Note: you might need to enable CORS)
