### ISSUE TITLE
RangeError: Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by deepak-jha-kgp** [AbelTesfaye/react-native-ytdl#36]
Getting `RangeError: Maximum call stack size exceeded`  if the video id contains `-`
Example video to test : [https://www.youtube.com/watch?v=u4-mu4YLFCA](https://www.youtube.com/watch?v=u4-mu4YLFCA)

**Comment by AbelTesfaye** [comment]
This should be fixed on the latest release

**Comment by deepak-jha-kgp** [comment]
awesome, thanks
