### ISSUE TITLE
Audio format download not working

### ISSUE THREAD

**Issue by ajoykarmakar** [AbelTesfaye/react-native-ytdl#38]
The library are working for downloading all audio format from the videos except some playlist from this channel. 
Channel URL - https://www.youtube.com/channel/UCc_qalKk-Zb3XrVA-SZdrXw
Example Playlist URL - https://www.youtube.com/watch?v=djasnrZO7rs&list=PLoPgsfk3OjvY5zP333l8jKNKL0PWYimfT

**Comment by AbelTesfaye** [comment]
Which video Ids are causing this?

And what is the error? Is it #39 ? If so then it should be fixed in the latest version

**Comment by ajoykarmakar** [comment]
This video isn't converting into playable audio URL. It's return some XML file. 
The YouTube video URL - https://www.youtube.com/watch?v=l2V3AepZkck&list=PLoPgsfk3OjvaG0Zn9FqFiEsnpFc4nfv6-
Example XML file - 
[AG3C_xAwRgIhAL5YuuG8Nbqo2O1qFvAMDj5drC1LzQvsXrth_QNM2UY_AiEAz_riSciAv8arYfmbLM7j3cNW1XPw55WEhQaY-Q6hEUE=.txt](https://github.com/AbelTesfaye/react-native-ytdl/files/5417249/AG3C_xAwRgIhAL5YuuG8Nbqo2O1qFvAMDj5drC1LzQvsXrth_QNM2UY_AiEAz_riSciAv8arYfmbLM7j3cNW1XPw55WEhQaY-Q6hEUE.txt)

**Comment by AbelTesfaye** [comment]
The xml file is a dash mpd playlist. You're getting this file because the quality you chose is available as a dash stream.

From this file, you can extract the segment urls you desire, download them and merge them into a single file.

**Comment by ajoykarmakar** [comment]
Thanks for the answer but can you please help me how to do it or can I set some condition to get only mp3 urls?

**Comment by ajoykarmakar** [comment]
Okay I have resolved the problem. For those who still searching the answer I am attaching a little code snippets that's help you. I have used react-native xml parser.

     fetch(audioFormats[0].url)
    .then((response) => response.text())
    .then((response) => {
      let xml = new XMLParser().parseFromString(response);
      console.log(xml.getElementsByTagName('BaseURL')[0].value);
    })
    .catch((err) => {
      console.log('fetch', err);
    });
  
Thanks.
