### ISSUE TITLE
Error: This video is unavailable

### ISSUE THREAD

**Issue by deepak-jha-kgp** [AbelTesfaye/react-native-ytdl#44]
Finding this new issue in some of the videos, while they're working just fine on youtube.
`Error: This video is unavailable`

Example links: 
https://youtu.be/d0VZ0rLXdOg
https://www.youtube.com/watch?v=xaY6Qzag0i0

**Comment by deepak-jha-kgp** [comment]
I noticed a trend, these videos have their embedding turned off

**Comment by AbelTesfaye** [comment]
This is interesting, there is a similar issue on node-ytdl-core too: https://github.com/fent/node-ytdl-core/issues/750

The video id thats not working cant be embedded as well

**Comment by deepak-jha-kgp** [comment]
This is solved in the latest version. Thanks.
