### ISSUE TITLE
File not found error on node_modules

### ISSUE THREAD

**Issue by ajoykarmakar** [AbelTesfaye/react-native-ytdl#47]
I think the screenshot is enough to describe the issue.
Version - 
    "react-native-ytdl": "^4.0.1",

![Screenshot_1604228144](https://user-images.githubusercontent.com/32778214/97800923-fbaf3800-1c5e-11eb-8cff-b4afe18a5ec3.png)

**Comment by AbelTesfaye** [comment]
The library works fine. Go to your react-native project root folder and run:

`npm uninstall react-native-ytdl` then `npm i react-native-ytdl@latest` reset transform cache if necessary, then it should work

**Comment by ajoykarmakar** [comment]
Yes works but I need to reset also the metro cache. 
npm start -- --reset-cache
Thanks.
