### ISSUE TITLE
How to download video using this npm module

### ISSUE THREAD

**Issue by heeropunjabi** [AbelTesfaye/react-native-ytdl#5]
Hi @AbelTesfaye,

First of all, Thanks for publishing this npm module !

I would to like to know how can we download video as part of the react-native.

I know this library has that limitation but what is the alternative ?

Thanks for passionate work you are doing !

Regards,
Heero Punjabi.
Be Calm & Compose Person.

**Comment by AbelTesfaye** [comment]
Hi,

Glad to hear this module was of help to you!

Since react-native doesn't have a built-in file downloader, you will need to use a 3rd party library for this task (maybe use rn-fetch-blob? https://www.npmjs.com/package/rn-fetch-blob)

The steps are pretty straightforward:

1. Once, you obtain a streamable link, file format and video title (ex. using `ytdl.getInfo`)
2. Pass the link to rn-fetch-blob. You can make the downloaded file name to be something like: `video_title.format`

I hope this clarifies any doubts you had.

Thanks.

**Comment by heeropunjabi** [comment]
@AbelTesfaye Let me try out this !

**Comment by heeropunjabi** [comment]
@AbelTesfaye can you pls help on the below code.

I m trying this :

componentDidMount() {
    videoID = "EkbM5EfFyME"
    ytdl.getInfo(videoID, {}, (err, info) => {
      if (err) console.log(err);
      let format = ytdl.chooseFormat(info.formats, { quality: '134' });
      if (format) {
        console.log('Info>>', info);
        this.setState({
          videoUrl: info.formats[0].url,
        })
        let dirs = RNFetchBlob.fs.dirs
        RNFetchBlob.config({
          // response data will be saved to this path if it has access right.
          // fileCache: true,
          // path: dirs.DCIMDir + '/my-video.mp4'
          addAndroidDownloads: {
            useDownloadManager: true, // <-- this is the only thing required
            // Optional, override notification setting (default to true)
            notification: true,
            // Optional, but recommended since android DownloadManager will fail when
            // the url does not contains a file extension, by default the mime type will be text/plain
            mime: 'video/mp4',
            description: 'File downloaded by download manager.'
          }
        }).fetch('GET', info.formats[0].url)
          // listen to download progress event, every 10%
          .progress({ count: 10 }, (received, total) => {
            console.log('progress', received / total)
          })
          .then((resp) => {
            // RNFetchBlob.fs.scanFile([{ path: res.path() }])
            console.log('The file saved to ', resp.path())
            console.log('resp', resp);
            Alert.alert(resp.path())
            // ...
          })
          .catch((err) => {
            // ...
            console.error(err);
          })


        //Alert.alert('Format found!', JSON.stringify(info));
      }
    });
  }

**Comment by AbelTesfaye** [comment]
I don't understand. What are the errors you are getting?

If the error is regarding format not being a video, then here's the fix:

```javascript
videoID = 'EkbM5EfFyME';
ytdl.getInfo(videoID, {}, (err, info) => {
    if (err) console.error(err);
    let format = ytdl.chooseFormat(info.formats, { quality: '134' });
    if (format) {
        console.log('Info>>', info);
        this.setState({
            videoUrl: format.url,
        });

        let dirs = RNFetchBlob.fs.dirs;
        RNFetchBlob.config({
            // response data will be saved to this path if it has access right.
            // fileCache: true,
            path: `${dirs.DownloadDir}/${info.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.${
                format.container
            }`,
            addAndroidDownloads: {
                useDownloadManager: true, // <-- this is the only thing required
                // Optional, override notification setting (default to true)
                notification: true,
                // Optional, but recommended since android DownloadManager will fail when
                // the url does not contains a file extension, by default the mime type will be text/plain
                mime: 'video/mp4',
                description: 'File downloaded by download manager.',
            },
        })
            .fetch('GET', format.url)
            // listen to download progress event, every 10%
            .progress({ count: 10 }, (received, total) => {
                console.log('progress', received / total);
            })
            .then(resp => {
                // RNFetchBlob.fs.scanFile([{ path: res.path() }])
                console.log('The file saved to ', resp.path());
                console.log('resp', resp);
                Alert.alert(resp.path());
                // ...
            })
            .catch(err => {
                // ...
                console.error(err);
            });

        //Alert.alert('Format found!', JSON.stringify(info));
    }
});

```

**Comment by heeropunjabi** [comment]
@AbelTesfaye Thank you so much. It worked Finally :)
You are an awesome Human Being !!
Keep Rocking.

**Comment by AbelTesfaye** [comment]
Cool, glad it worked!
