### ISSUE TITLE
Support for mp3 and all video format.

### ISSUE THREAD

**Issue by heeropunjabi** [AbelTesfaye/react-native-ytdl#6]
Hi @AbelTesfaye,
I hope you are doing absolutely an amazing things in your life !

I need one help to understand one thing.

Query is : How can I download all the formats which are coming as part of the formats property.
So let's take an example.
![image](https://user-images.githubusercontent.com/3514019/59132750-abfa0d80-8993-11e9-93eb-60e0439333e0.png)

As you can see in the above attached image we have list of 7 formats.

When I am downloading it using it's url property within formats array,  its downloading but when i m playing it its mute !!!.

One more query on top of it > how can v download mp3 files also.

Thanks In Advance !

Regards,
Heero Punjabi.

**Comment by AbelTesfaye** [comment]
Hello,

1. For some videos YouTube provides separate urls for audio and video, and later merges them in it player (https://github.com/fent/node-ytdl-core#handling-separate-streams). So I guess you'll probably need to do the same. Download audio and video separately then merge them manually (try this library maybe? https://www.npmjs.com/package/react-native-ffmpeg).

2. I don't think YouTube provides mp3 formats, so If you want mp3 formats I guess you'll need to convert whatever is available.
