### ISSUE TITLE
default.downloadFromInfo is not a function

### ISSUE THREAD

**Issue by idoor88** [AbelTesfaye/react-native-ytdl#9]
Hi, I am trying to test downloading a youtube video with the following code, but got error saying: downloadFromInfo is not a function:

`videoID = "04GiqLjRO3A";

        ytdl.getInfo(videoID, {}, (err, info) => {

            console.log("componentDidMount info: ", info);

            if (err) console.log(err);

            let vd = ytdl.downloadFromInfo(info, {});

            console.log('found vd: ', vd);`

So any idea what is going on? I checked your ytdl.js file, there is no downloadFromInfo function in there.

Thanks

**Comment by jibbex** [comment]
Hello, 

ytdl-core uses [m3u8stream](https://www.npmjs.com/package/m3u8stream) to download files. Unfortunately this package is not available for react-native. You could use [rn-fetch-blob](https://github.com/joltup/rn-fetch-blob) instead. But for Android apps i would honestly stick to the the native Android Download Manager. Just get the wanted url with ytdl.ChooseFormat and choose you preferred method to download.


```
ytdl.getInfo(videoID, {}, (err, info) => {
  const format = ytdl.chooseFormat(info.formats, { quality: 'highest'});

  RNFetchBlob.config({
    fileCache : true,
  }).fetch('GET', format.url, {}).then((res) => {
    console.log('The file saved to ', res.path())
  })
})
```

**Comment by idoor88** [comment]
Got you, thanks
